### ISSUE TITLE
Couldn't Sign In

### ISSUE THREAD

**Issue by zerofltexx** [a-h/pill#6]
Hi Adrian,

I'd set up pill inside my Windows machine but I couldn't sign in to the web app. Here's the log that I got from my command prompt

![1](https://cloud.githubusercontent.com/assets/15305422/22958982/bb730a8c-f36d-11e6-80e6-bec9d84e27ab.PNG)

I kept getting "The presented claim is invalid" error from the web app after multiple tries. I'm not familiar with OAuth :(

**Comment by a-h** [comment]
Are you running it inside a Docker container? I Googled the error message and the results were all related to Docker. Also, if you're running inside a corporate environment where SSL traffic is decrypted, maybe you'd see the same error.

Can you CURL to https://www.googleapis.com from the machine without error?

**Comment by zerofltexx** [comment]
I'm on corporate network. Tested it with my home network and now everything works fine. Thanks!
